# Site settings

# Permalink, markdown and highlighter
permalink: /blog/:year/:month/:title/

# SEO settings
title:
description: > # this means to ignore newlines until "baseurl:"
  A blog on geeky stuff
keywords:


# Author settings
author:
    name:             Alessandra Gherardelli
    # facebook:         alexgherardelli
    # twitter:          your-id
    github:           AlexGherardelli
    linkedin:         alessandragherardelli
    # medium:           your-id
    # tumblr:           your-id
    # dribble:          your-id
    # behance:          alexgherardelli
    email:           alessandra.gherardelli@gmail.com

# Timezones
timezone:           Europe/Rome

# Collections settings
collections:
    work:
        # permalink: /projects/:path/
    projects:
    past-positions:

# Sass 
sass:
  sass_dir: sass
  style: extended

# Pagination
pagination: 
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title'
  sort_reverse: true

# Markdown
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
gems:
  - jekyll-email-protect
  - jekyll-paginate-v2
  - jekyll-seo-tag
  
