# Site settings

# Permalink, markdown and highlighter
permalink: /blog/:year/:month/:title/

# SEO settings
<<<<<<< HEAD
title: Alessandra Gherardelli | Product & Project manager
description:  Alessandra Gherardelli is a product/project manager with 8 years of experience in driving communications and information management projects in the United Nations system
keywords: 
=======
title: Alessandra Gherardelli | Communications + Data + Design
description: 
keywords: data, dataviz, tech, design, communications
>>>>>>> b6ba815a9a0edafc3c308a0fb8240712bdab8c27


# Author settings
author:
    name:             Alessandra Gherardelli
    github:           AlexGherardelli
    linkedin:         alessandragherardelli
    tableau:          alexgherardelli
    # medium:           your-id
    # tumblr:           your-id
    # dribble:          your-id
<<<<<<< HEAD
=======
    # tableau:        id
>>>>>>> b6ba815a9a0edafc3c308a0fb8240712bdab8c27
    # behance:         gherds
    email:           alessandra.gherardelli@gmail.com
    description:     I am a versatile, tech-savvy professional with 8 years of experience in driving communications and information management projects in international organizations. Currently I work for the World Food Programme (WFP), the leading humanitarian agency fighting hunger in 80+ countries and recipient of the 2020 Nobel Peace Prize.

# Timezones
timezone:           Europe/Rome

# Collections settings
collections:
    work:
        # permalink: /projects/:path/
    projects:


# Sass 
sass:
  sass_dir: sass
  style: extended

# Pagination
pagination: 
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title'
  sort_reverse: true

# Markdown
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
gems:
  - jekyll-email-protect
  # - jekyll-paginate-v2
  - jekyll-seo-tag

  
  
  
